### ISSUE TITLE
Main page UI 배치

### ISSUE THREAD

**Issue by HyeockJinKim** [Just-Game/Just-Game-app#3]
초안에 따른 Main page UI 배치

**Comment by rinha7** [comment]
![just-game-app_190128](https://user-images.githubusercontent.com/45866425/51822262-0bc61500-231f-11e9-843d-aafd191ac33a.jpeg)

**Comment by rinha7** [comment]
![just-game-app_tab2](https://user-images.githubusercontent.com/45866425/52108309-d5e5a100-263c-11e9-9979-7738af68b3fd.png)

**Comment by HyeockJinKim** [comment]
서버에서 보내주는 데이터 형식
```JSON
{
  "name": "GAMENAME",
  "description": "Game_Description",
  "update_note": "Game_Update_Note",
  "game_down_link": "Link"
}
```

**Comment by rinha7** [comment]
메인페이지 UI를 어떻게 바꾸어야 할 지 상의가 필요할듯
