### ISSUE TITLE
게임 클릭 시 Tab 추가되는 기능

### ISSUE THREAD

**Issue by HyeockJinKim** [Just-Game/Just-Game-app#5]
### 좌측에 있는 Game의 이름을 클릭했을 경우
- 우측의 Tab에 게임의 이름이 뜨면서 추가되게 변경  
- 그리고 게임에 맞는 Tab이 열리게 만들어야 함  
- Tab에는 게임의 이름이 적혀야 함
-------------------------------------------
![img](https://user-images.githubusercontent.com/45866425/51822262-0bc61500-231f-11e9-843d-aafd191ac33a.jpeg)

**Comment by rinha7** [comment]
![_190207](https://user-images.githubusercontent.com/45866425/52387810-f5fae180-2ace-11e9-94f6-b4869cdfa469.png)

구현 완료

**Comment by rinha7** [comment]
우선 작성하여 커밋함

아직 구현하지 못한 것

 - recentGame을 눌렀을때도 반영
 - 기존에 열린 탭이 있으면 새로 추가 하는 것이 아닌 그쪽으로 이동하는 기능

**Comment by rinha7** [comment]
recentGame을 눌렀을때도 반영하도록 수정하여 커밋함(issues5)

**Comment by rinha7** [comment]
![190208_gamepage](https://user-images.githubusercontent.com/45866425/52466377-70a62880-2bc5-11e9-8927-7ad310e7536a.png)

구현 완료.

closes https://github.com/Just-Game/Just-Game-app/issues/5

**Comment by rinha7** [comment]
![ui](https://user-images.githubusercontent.com/45866425/52531107-a11bcd00-2d53-11e9-92d7-28a0032c8484.png)
